# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187261d9a73a10214b4ba02e8deb6ce9fe37112a73f8e900476b2a209362f6ebf01aa8cdbe511982a8392d605c3a0630b1b5ad4368960e39dfb59ec645759db8

test:
  secret_key_base: ded6c0de0576dca74c72896948eeb9391cec70e412f72be635770b0a47b8ddad0f13a18b7760b9258f08937ce904a7f002d9567d9b0dcb82ec1ff6b15e4cb151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
